Add CI workflow
canonical/prometheus-juju-exporter pull request #2
Opened 2022-11-29 19:19 UTC by agileshaw

2022-11-30 14:05 UTC, esunar commented
Can you follow this [guide](https://docs.google.com/document/d/1tPegHJUrGbAYTcIPrj5wqKPw821g7ddIMWLAGw4WNgg/edit#heading=h.nifye65eyxo) with unit tests and sonarqube integration

2022-11-30 14:06 UTC, esunar requested changes
Can you follow this [guide](https://docs.google.com/document/d/1tPegHJUrGbAYTcIPrj5wqKPw821g7ddIMWLAGw4WNgg/edit#heading=h.nifye65eyxo) with unit tests and sonarqube integration

2022-12-01 06:54 UTC, Pjack approved these changes
LGTM

2022-12-01 14:04 UTC, esunar approved these changes

2022-12-02 00:45 UTC, aieri approved these changes

2022-12-02 00:48 UTC, merged