Remove old files and use new templates
canonical/prometheus-juju-exporter pull request #90
Opened 2024-11-01 11:06 UTC by samuelallan72

Note that check.yaml differs from the snap_check template in automation, because currently the snap_check template does not have a job for unit tests.

2024-11-07 21:36 UTC, rgildein requested changes

2024-11-07 21:36 UTC, rgildein commented on .github/workflows/release.yaml
> +          release: latest/edge
We need to release to both channels.

2024-11-14 14:54 UTC, samuelallan72 commented on .github/workflows/release.yaml
> +          release: latest/edge
Thanks, addressed :)

2024-11-18 01:26 UTC, jneo8 commented
Re-trigger functional test

2024-11-18 09:11 UTC, rgildein submitted a review, later dismissed
LGTM, however, maybe we will need to fix func test for Python 3.10.

2024-11-22 02:57 UTC, chanchiwai-ray approved these changes
A reminder to also update: https://github.com/canonical/solutions-engineering-automation/blob/main/.github/workflows/weekly_tests.yaml#L51

2024-11-22 05:04 UTC, samuelallan72 commented
Thanks @chanchiwai-ray , added in https://github.com/canonical/solutions-engineering-automation/pull/116 :)

2024-11-22 09:11 UTC, rgildein approved these changes

2024-11-24 22:53 UTC, merged